Feature/simple player
OKTW-Network/live-frontend pull request #5
Opened 2023-11-13 15:07 UTC by jimchen5209

## Base
- #4 

## Changes
- Add custom player and remove info bar

## Maybe todo
- seek bar and volume bar styling

2023-11-15 09:06 UTC, asdf3601a commented
這個 PR 我是這樣理解
1. 更好的顯示標題的方式
2. 與播放器融合在一起的畫質選項

個人是想先留著這個 PR 觀察一下
原因是這樣
1. 畫質選擇是鮮少用到的功能
2. 瀏覽器自帶的播放器應該會更能夠適應它自己在的使用情境
3. 直播紀錄並沒有明確的"標題"，在這裡只是把時間和 streamer 顯示出來讓使用者更好分辨現在正在欣賞誰的影片。
綜上所述，我認為讓播放器可以顯示標題和畫質選項之類的更像是幫它做個「主題」的改動應該先保留。

2023-11-15 09:36 UTC, james58899 requested changes

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +  }, 3.5 * 1000)
隱藏overlay時間太久

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +  if (currentTime.value + 5 <= duration.value)
改用 `Math.min()`

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +  { value: 4, text: '4x' }
我們需要5倍

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +const onDblClick = (event) => {
Dbl?

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +  video.value.muted = !video.value.muted
暫停時不會更新靜音圖示

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +            <input type="range" class="mobile:has-hidden" v-model="volume" :max="100" @input="setVolume" @wheel="onMouseWheel" />
靜音時不會將音量條歸0

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +const onMouseWheel = (event) => {
這個命名與音量毫無關係

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +            <input type="range" class="mobile:has-hidden" v-model="volume" :max="100" @input="setVolume" @wheel="onMouseWheel" />
使用滾輪調整音量時overlay隱藏倒數不會重置

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +  if (volume.value + 10 <= 100)
音量調整一次10%太多

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +            <input type="range" class="mobile:has-hidden" v-model="volume" :max="100" @input="setVolume" @wheel="onMouseWheel" />
滑鼠游標指上去不會提示目前音量

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +        <input
滑鼠游標不會變成手指

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +  const seconds = Math.floor(time - hour * 3600 - minutes * 60)
直接用 `%` 計算，並且改用 `Math.round()`

2023-11-15 09:36 UTC, james58899 commented on src/components/centerBlock/OverlayPlayer.vue
> +    case 'm':
聊天室無法輸入m

2023-11-15 10:18 UTC, asdf3601a commented on src/components/centerBlock/OverlayPlayer.vue
> +const toggleMute = () => {
靜音的時候音量條應該歸零

2023-11-15 10:18 UTC, asdf3601a commented on src/components/centerBlock/OverlayPlayer.vue
> +        <input
`step="any"` 這條就拉起來就不會一格一格

2023-11-15 10:42 UTC, asdf3601a commented
寬度 < 384px 播放器底下那條的全螢幕按鈕會塞不下直接跑出螢幕

2023-11-15 10:43 UTC, asdf3601a commented
畫面橫過來沒辦法用
![圖片](https://github.com/OKTW-Network/live-frontend/assets/12381354/85fa6234-dab0-441f-8e0c-2f29fff255fe)

2023-11-15 10:52 UTC, asdf3601a commented
> 畫面橫過來沒辦法用 ![圖片](https://user-images.githubusercontent.com/12381354/283090293-85fa6234-dab0-441f-8e0c-2f29fff255fe.png)

阿喔 這個問題 main 上就有

issue #6

2023-11-15 12:13 UTC, jimchen5209 commented
> 寬度 < 384px 播放器底下那條的全螢幕按鈕會塞不下直接跑出螢幕

Fixed by replacing to icon

2023-11-20 07:30 UTC, james58899 submitted a review, later dismissed
1. 靜音無法使用音量條解除
2. 靜音時無法使用滾輪調整音量且在解除靜音後會變成0%或5%而不是原始音量
3. 點開調整速度選單時介面不會持續顯示
4. 游標是手指時不會跟著介面消失
5. 直播缺少總時長

2023-11-20 17:13 UTC, asdf3601a commented
1. 在 Streamer 頁面點影片和 Top 按鈕不會回到最頂部了
2. 在比較短的影片裡底下那條進度條拉起來一格一格的（那條的 input 的 Step 應該是 any）

2023-11-21 04:07 UTC, jimchen5209 commented
> 1. 在 Streamer 頁面點影片和 Top 按鈕不會回到最頂部了

#9

2023-11-24 14:36 UTC, asdf3601a approved these changes

2023-11-24 14:36 UTC, merged